/**
 * Federal worksheets: bracket tax / tax-table emulation, the Qualified
 * Dividends and Capital Gain Tax Worksheet, the Social Security Benefits
 * Worksheet, Schedule SE, and the EITC computation.
 *
 * All functions are pure, take whole-dollar cent amounts, and return
 * whole-dollar cent amounts, matching the way IRS worksheets round at each
 * numbered line.
 */
import {
  type Cents,
  type FilingStatus,
  centsToWholeDollars,
  maxCents,
  minCents,
  multiplyRate,
  notLessThanZero,
} from "@ghimtech/tax-domain";
import type { EitcParameters, FederalYearConfig, TaxBracket } from "@ghimtech/tax-year-config";

/** Round cents to whole-dollar cents using IRS rounding. */
export function rd(cents: Cents): Cents {
  return centsToWholeDollars(cents) * 100;
}

/** Marginal tax on `taxableIncome` using the bracket schedule (Tax Computation Worksheet). */
export function bracketTax(taxableIncome: Cents, brackets: TaxBracket[]): Cents {
  let tax = 0;
  for (let i = 0; i < brackets.length; i++) {
    const bracket = brackets[i]!;
    const next = brackets[i + 1];
    const upper = next ? next.over : Number.MAX_SAFE_INTEGER;
    if (taxableIncome <= bracket.over) break;
    const amountInBracket = minCents(taxableIncome, upper) - bracket.over;
    tax += Math.round(amountInBracket * bracket.rate);
  }
  return tax;
}

/**
 * IRS Tax Table emulation for taxable income under $100,000.
 *
 * The published table is generated by applying the rate schedule to the
 * midpoint of each income range: $25-wide ranges under $3,000 (with $5/$10
 * ranges under $25) and $50-wide ranges from $3,000 to $100,000. Emulating
 * the generation rule reproduces the printed table exactly.
 */
export function taxFromTableOrSchedule(taxableIncome: Cents, brackets: TaxBracket[]): Cents {
  if (taxableIncome <= 0) return 0;
  const hundredK = 100_000 * 100;
  if (taxableIncome >= hundredK) {
    return rd(bracketTax(taxableIncome, brackets));
  }
  let midpoint: Cents;
  const fiveDollars = 5 * 100;
  const fifteen = 15 * 100;
  const twentyFive = 25 * 100;
  const threeThousand = 3_000 * 100;
  if (taxableIncome < fiveDollars) {
    midpoint = Math.round(fiveDollars / 2);
  } else if (taxableIncome < fifteen) {
    midpoint = 10 * 100;
  } else if (taxableIncome < twentyFive) {
    midpoint = 20 * 100;
  } else if (taxableIncome < threeThousand) {
    const lower = Math.floor(taxableIncome / (25 * 100)) * (25 * 100);
    midpoint = lower + Math.round((25 * 100) / 2);
  } else {
    const lower = Math.floor(taxableIncome / (50 * 100)) * (50 * 100);
    midpoint = lower + 25 * 100;
  }
  return rd(bracketTax(midpoint, brackets));
}

/**
 * Qualified Dividends and Capital Gain Tax Worksheet (Form 1040 instructions).
 * Applies preferential rates to qualified dividends and capital gain
 * distributions; ordinary rates to the rest.
 */
export function qualifiedDividendsCapGainTax(params: {
  taxableIncome: Cents;
  qualifiedDividends: Cents;
  capitalGainDistributions: Cents;
  filingStatus: FilingStatus;
  config: FederalYearConfig;
}): Cents {
  const { taxableIncome, qualifiedDividends, capitalGainDistributions, filingStatus, config } =
    params;
  const brackets = config.brackets[filingStatus];
  const { zeroRateMax, fifteenRateMax } = config.capitalGains[filingStatus];

  const line1 = taxableIncome;
  const line2 = qualifiedDividends;
  const line3 = capitalGainDistributions; // no Schedule D in supported scope
  const line4 = rd(line2 + line3); // preferential-rate income
  const line5 = notLessThanZero(line1 - line4); // ordinary-rate income
  const line6 = zeroRateMax;
  const line7 = minCents(line1, line6);
  const line8 = minCents(line5, line7);
  const line9 = notLessThanZero(line7 - line8); // taxed at 0%
  const line10 = minCents(line1, line4);
  const line11 = line9;
  const line12 = notLessThanZero(line10 - line11);
  const line13 = fifteenRateMax;
  const line14 = minCents(line1, line13);
  const line15 = line5 + line9;
  const line16 = notLessThanZero(line14 - line15);
  const line17 = minCents(line12, line16); // taxed at 15%
  const line18 = rd(multiplyRate(line17, 0.15));
  const line19 = line9 + line17;
  const line20 = notLessThanZero(line10 - line19); // taxed at 20%
  const line21 = rd(multiplyRate(line20, 0.2));
  const line22 = taxFromTableOrSchedule(line5, brackets); // ordinary income tax
  const line23 = line18 + line21 + line22;
  const line24 = taxFromTableOrSchedule(line1, brackets); // tax on all income at ordinary rates
  return minCents(line23, line24);
}

/**
 * Social Security Benefits Worksheet (Form 1040 instructions).
 * Returns the taxable portion of net benefits.
 */
export function taxableSocialSecurity(params: {
  netBenefits: Cents;
  /** AGI computed without social security. */
  otherIncome: Cents;
  taxExemptInterest: Cents;
  filingStatus: FilingStatus;
  config: FederalYearConfig;
}): Cents {
  const { netBenefits, otherIncome, taxExemptInterest, filingStatus, config } = params;
  if (netBenefits <= 0) return 0;
  const base = config.socialSecurityTaxability.baseAmount[filingStatus];
  const adjustedBase = config.socialSecurityTaxability.adjustedBaseAmount[filingStatus];
  const half = rd(Math.round(netBenefits / 2));
  const provisional = half + otherIncome + taxExemptInterest;
  if (provisional <= base) return 0;
  const overBase = provisional - base;
  if (provisional <= adjustedBase) {
    return minCents(rd(Math.round(overBase / 2)), half);
  }
  const overAdjusted = provisional - adjustedBase;
  const tier1 = minCents(rd(Math.round((adjustedBase - base) / 2)), half);
  const tier2 = rd(multiplyRate(overAdjusted, config.socialSecurityTaxability.tier2Rate));
  return minCents(
    tier1 + tier2,
    rd(multiplyRate(netBenefits, config.socialSecurityTaxability.tier2Rate)),
  );
}

export interface SeTaxResult {
  /** Net earnings from self-employment (Schedule SE line 4a/4c). */
  netEarnings: Cents;
  seTax: Cents;
  /** Deduction for one-half of SE tax. */
  halfSeTaxDeduction: Cents;
}

/** Schedule SE. `netProfit` is combined Schedule C net profit; `w2SocialSecurityWages` caps the SS portion. */
export function seTax(params: {
  netProfit: Cents;
  w2SocialSecurityWages: Cents;
  config: FederalYearConfig;
}): SeTaxResult {
  const { netProfit, w2SocialSecurityWages, config } = params;
  const cfg = config.selfEmployment;
  if (netProfit <= 0) return { netEarnings: 0, seTax: 0, halfSeTaxDeduction: 0 };
  const netEarnings = rd(multiplyRate(netProfit, cfg.netEarningsFactor));
  if (netEarnings < cfg.filingThreshold) {
    return { netEarnings, seTax: 0, halfSeTaxDeduction: 0 };
  }
  const ssBaseRemaining = notLessThanZero(cfg.socialSecurityWageBase - w2SocialSecurityWages);
  const ssTaxable = minCents(netEarnings, ssBaseRemaining);
  const ssTax = rd(multiplyRate(ssTaxable, cfg.socialSecurityRate));
  const medicareTax = rd(multiplyRate(netEarnings, cfg.medicareRate));
  const total = ssTax + medicareTax;
  return {
    netEarnings,
    seTax: total,
    halfSeTaxDeduction: rd(Math.round(total / 2)),
  };
}

export interface EitcInput {
  earnedIncome: Cents;
  agi: Cents;
  investmentIncome: Cents;
  qualifyingChildren: number; // 0..3+ (capped at 3)
  filingStatus: FilingStatus;
  /** Taxpayer age at end of the tax year (and spouse's, for the no-child age test). */
  taxpayerAge: number;
  spouseAge?: number;
  params: EitcParameters;
}

export interface EitcResult {
  eligible: boolean;
  ineligibleReason?: string;
  credit: Cents;
}

/** Earned Income Tax Credit computation with eligibility gates. */
export function earnedIncomeCredit(input: EitcInput): EitcResult {
  const { params } = input;
  const kids = Math.min(input.qualifyingChildren, 3);

  if (input.filingStatus === "MARRIED_FILING_SEPARATELY") {
    return {
      eligible: false,
      ineligibleReason: "MFS filers are not eligible for the EITC",
      credit: 0,
    };
  }
  if (input.investmentIncome > params.investmentIncomeLimit) {
    return {
      eligible: false,
      ineligibleReason: "Investment income exceeds the EITC limit",
      credit: 0,
    };
  }
  if (kids === 0) {
    const taxpayerOk = input.taxpayerAge >= 25 && input.taxpayerAge < 65;
    const spouseOk =
      input.spouseAge === undefined ? false : input.spouseAge >= 25 && input.spouseAge < 65;
    const ageOk =
      input.filingStatus === "MARRIED_FILING_JOINTLY" ? taxpayerOk || spouseOk : taxpayerOk;
    if (!ageOk) {
      return {
        eligible: false,
        ineligibleReason: "Without a qualifying child, the taxpayer (or spouse) must be 25-64",
        credit: 0,
      };
    }
  }
  if (input.earnedIncome <= 0) {
    return { eligible: false, ineligibleReason: "No earned income", credit: 0 };
  }

  const creditRate = params.creditRate[kids]!;
  const earnedAmount = params.earnedIncomeAmount[kids]!;
  const phaseoutRate = params.phaseoutRate[kids]!;
  const phaseoutStart =
    input.filingStatus === "MARRIED_FILING_JOINTLY"
      ? params.phaseoutStartMfj[kids]!
      : params.phaseoutStart[kids]!;

  const maxCredit = rd(multiplyRate(earnedAmount, creditRate));

  // The published EITC table is generated from $50-wide income ranges; each
  // row's credit is computed at the range midpoint. Emulating the generation
  // rule reproduces the printed table.
  const tableCredit = (income: Cents): Cents => {
    const fifty = 50 * 100;
    const mid = Math.floor(income / fifty) * fifty + fifty / 2;
    const rampSide = minCents(rd(multiplyRate(minCents(mid, earnedAmount), creditRate)), maxCredit);
    const phasedSide =
      mid > phaseoutStart
        ? notLessThanZero(rd(maxCredit - multiplyRate(mid - phaseoutStart, phaseoutRate)))
        : maxCredit;
    return minCents(rampSide, phasedSide);
  };

  const credit = minCents(
    tableCredit(input.earnedIncome),
    tableCredit(maxCents(input.agi, input.earnedIncome)),
  );
  if (credit === 0) {
    return {
      eligible: false,
      ineligibleReason: "Income above the EITC phase-out limit",
      credit: 0,
    };
  }
  return { eligible: true, credit };
}
