"use client";

import { motion } from "framer-motion";
import { SectionHeader } from "@/components/shared/section-header";

/**
 * Stylized world map.
 *
 * Pure SVG, no external map service. The world is represented as a dot
 * matrix in the bottom layer, with two glowing markers — Nepal (origin)
 * and the United States (current base) — connected by an arc that
 * traces from origin to now.
 *
 * The dot matrix is generated by sampling a path approximation of the
 * continents at a coarse resolution. It looks intentional and abstract,
 * not like a failed map.
 */
export function WorldMap() {
  return (
    <section className="relative py-24 lg:py-32 border-t border-white/5">
      <div className="container">
        <SectionHeader
          eyebrow="Reach"
          title={
            <>
              From <span className="text-gradient-vital">Nepal</span> to the{" "}
              <span className="text-gradient-signal">United States</span>.
            </>
          }
          sub="Based in the US, building for agencies across the country. Open to conversations from anywhere."
        />

        <motion.div
          initial={{ opacity: 0, scale: 0.96 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true, margin: "-50px" }}
          transition={{ duration: 1.2, ease: [0.22, 1, 0.36, 1] }}
          className="mt-14 glass-panel-strong p-6 lg:p-10 relative overflow-hidden hud-corners"
        >
          <span className="hud-corner-tl" aria-hidden />
          <span className="hud-corner-br" aria-hidden />

          {/* Glow behind map */}
          <div
            aria-hidden
            className="absolute -inset-20 bg-signal-400/5 blur-3xl"
          />

          {/* Status bar above map */}
          <div className="relative flex items-center justify-between mb-6">
            <span className="label-tactical">Global · live tracking</span>
            <span className="flex items-center gap-1.5 font-mono text-[10px] text-vital-300">
              <span className="status-dot status-dot-live" />
              2 nodes active
            </span>
          </div>

          {/* The map */}
          <DotMatrixWorld />

          {/* Legend */}
          <div className="mt-6 flex flex-wrap items-center gap-6 text-xs font-mono">
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-vital-400 shadow-glow-vital animate-pulse-vital" />
              <span className="text-zinc-400">
                <span className="text-vital-300">Origin</span> · Nepal
              </span>
            </div>
            <div className="flex items-center gap-2">
              <span className="h-2 w-2 rounded-full bg-signal-400 shadow-glow-signal animate-pulse-signal" />
              <span className="text-zinc-400">
                <span className="text-signal-300">Now</span> · United States
              </span>
            </div>
            <div className="flex items-center gap-2 ml-auto">
              <span className="block h-px w-6 bg-gradient-to-r from-vital-400 to-signal-400" />
              <span className="text-zinc-500">Journey</span>
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}

/* ============================================================
   Dot-matrix world map.
   The continents are approximated by a coarse grid of dots inside
   roughly-shaped regions. This is intentionally stylized — it's
   not meant to be cartographically precise, it's meant to look
   like a HUD globe readout.
   ============================================================ */

// Simplified continent dot positions. Each region is a list of [x, y] points
// in a 0..100 SVG coordinate space. Hand-tuned to look balanced.
const CONTINENT_DOTS = generateContinentDots();

function DotMatrixWorld() {
  // Marker positions tuned to look right within the simplified continent shapes
  const nepal = { x: 70, y: 38 };
  const usa = { x: 22, y: 33 };

  return (
    <div className="relative aspect-[2/1] w-full">
      <svg
        viewBox="0 0 100 50"
        preserveAspectRatio="xMidYMid meet"
        className="absolute inset-0 w-full h-full"
      >
        {/* Soft latitude lines */}
        {[10, 20, 30, 40].map((y) => (
          <line
            key={y}
            x1={0}
            y1={y}
            x2={100}
            y2={y}
            stroke="rgba(255,255,255,0.04)"
            strokeWidth={0.1}
            strokeDasharray="0.4 0.6"
          />
        ))}

        {/* Continent dots */}
        {CONTINENT_DOTS.map(([x, y], i) => (
          <circle
            key={i}
            cx={x}
            cy={y}
            r={0.3}
            fill="rgba(255,255,255,0.18)"
          />
        ))}

        {/* Arc from Nepal → USA */}
        <motion.path
          d={`M ${nepal.x} ${nepal.y} Q 50 8 ${usa.x} ${usa.y}`}
          fill="none"
          stroke="url(#journeyGradient)"
          strokeWidth={0.3}
          strokeLinecap="round"
          initial={{ pathLength: 0, opacity: 0 }}
          whileInView={{ pathLength: 1, opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 2.4, ease: [0.22, 1, 0.36, 1] }}
        />

        {/* Gradient stop for the arc */}
        <defs>
          <linearGradient id="journeyGradient" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" stopColor="#1fe294" />
            <stop offset="100%" stopColor="#3aa4ff" />
          </linearGradient>
        </defs>

        {/* Nepal marker — origin */}
        <Marker x={nepal.x} y={nepal.y} color="#1fe294" delay={0.3} />

        {/* USA marker — now */}
        <Marker x={usa.x} y={usa.y} color="#3aa4ff" delay={0.6} />
      </svg>

      {/* Corner readouts overlay */}
      <div className="absolute top-2 left-2 font-mono text-[9px] text-zinc-500 tracking-tactical">
        85°N
      </div>
      <div className="absolute bottom-2 right-2 font-mono text-[9px] text-zinc-500 tracking-tactical">
        ghimtech.org / map
      </div>
    </div>
  );
}

function Marker({
  x,
  y,
  color,
  delay,
}: {
  x: number;
  y: number;
  color: string;
  delay: number;
}) {
  return (
    <g>
      {/* Outer pulse ring */}
      <motion.circle
        cx={x}
        cy={y}
        r={1}
        fill="none"
        stroke={color}
        strokeWidth={0.15}
        initial={{ scale: 0, opacity: 0 }}
        animate={{ scale: [1, 2.5, 1], opacity: [0.8, 0, 0.8] }}
        transition={{
          duration: 3,
          repeat: Infinity,
          delay,
          ease: [0.65, 0, 0.35, 1],
        }}
      />
      {/* Inner glow */}
      <motion.circle
        cx={x}
        cy={y}
        r={1.2}
        fill={color}
        initial={{ scale: 0, opacity: 0 }}
        whileInView={{ scale: 1, opacity: 0.3 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6, delay, ease: [0.22, 1, 0.36, 1] }}
        style={{ filter: "blur(0.5px)" }}
      />
      {/* Solid dot */}
      <motion.circle
        cx={x}
        cy={y}
        r={0.7}
        fill={color}
        initial={{ scale: 0 }}
        whileInView={{ scale: 1 }}
        viewport={{ once: true }}
        transition={{
          type: "spring",
          stiffness: 280,
          damping: 18,
          delay: delay + 0.1,
        }}
      />
    </g>
  );
}

/**
 * Generate a simplified continent dot matrix.
 * Each entry is [x, y] in a 0..100 / 0..50 coordinate space.
 * Continents are approximated as filled regions with dots on a 1.5-unit grid.
 */
function generateContinentDots(): Array<[number, number]> {
  // Define continents as bounding regions made of rectangles
  // (x1, y1, x2, y2). Dots are placed on a grid inside.
  // Coordinates were hand-tuned to look balanced on the 100x50 canvas.
  const REGIONS = [
    // North America
    { rect: [12, 18, 32, 32] as const, density: 0.7 },
    { rect: [8, 22, 14, 30] as const, density: 0.5 },
    { rect: [16, 14, 28, 20] as const, density: 0.5 },
    // South America
    { rect: [22, 32, 32, 46] as const, density: 0.7 },
    // Europe
    { rect: [46, 18, 56, 25] as const, density: 0.7 },
    // Africa
    { rect: [48, 26, 58, 42] as const, density: 0.7 },
    // Russia / Asia north
    { rect: [56, 14, 84, 22] as const, density: 0.6 },
    // Middle East
    { rect: [58, 24, 66, 30] as const, density: 0.6 },
    // India / SE Asia
    { rect: [66, 26, 76, 36] as const, density: 0.7 },
    // China / East Asia
    { rect: [74, 20, 84, 28] as const, density: 0.7 },
    // Japan
    { rect: [85, 24, 89, 30] as const, density: 0.5 },
    // Australia
    { rect: [80, 36, 92, 44] as const, density: 0.7 },
    // UK / Scandinavia
    { rect: [44, 14, 52, 20] as const, density: 0.5 },
    // Greenland
    { rect: [38, 8, 46, 16] as const, density: 0.4 },
  ];

  const points: Array<[number, number]> = [];
  const step = 1.5;

  for (const region of REGIONS) {
    const [x1, y1, x2, y2] = region.rect;
    for (let y = y1; y <= y2; y += step) {
      for (let x = x1; x <= x2; x += step) {
        // Use a simple deterministic "noise" so it looks organic, not gridded
        const n = (Math.sin(x * 12.9898 + y * 78.233) * 43758.5453) % 1;
        if (Math.abs(n) < region.density) {
          points.push([x, y]);
        }
      }
    }
  }

  return points;
}
